### PR TITLE
Feature/follow log #18

### PR DESCRIPTION
**Pull request by mauricekraus**

### CODE REVIEW

**Comment by mauricekraus** [comment]
Updated pull request for #18

**Comment by Azbagheri** [comment]
Before diving into the technical details of the changes, I have some feedback on the PR. I tested your changes locally and noticed that the streamed logs don't have the same formatting as the ones we currently have. For example, tables are broken and there is no coloured text. We will definitely want to provide the same user experience no matter how the logs are provided. So please get your formatting in line with our existing formatting.

The second point is that in our first discussion, we talked about giving the users the option to change the polling interval. Is there a reason that you did not implement this in the PR?

**Comment by Azbagheri** [comment]
The pipeline fix has been merged into develop! Please update your branch to get the fix.

**Comment by mauricekraus** [comment]
This is very strange, since I tested it locally in my own gitlab installation, as well as in my terminal. Everything seems to work here. What kind of terminal do you use bash or zsh?
image

Yeah, I left it out on purpose. Currently I use a polling interval of 5 seconds (something similar is used by gitrise itself, they don't use a socket connection), because anything bigger could lead to the situation that log messages are lost.
An example scenario would be, I request the first log and get log positions 1 to 10, wait a minute and in the meantime the build is finished. Since gitrise does not send the whole log in chunks after completion, I probably only get 17-25 and logs 10 to 17 are lost. By not giving the user the possibility to specify the interval, I avoid this problem, because even if the build is finished a bit earlier, it will not happen that I am so far away (i.e. that such large distances as 10 to 17 occur).
As you can see, I don't use the specified gitrise api, but have reverse engineered the actual api used by gitrise itself. This allows to specify a timestamp that gives me only unread chunks. Unfortunately the final log is not divided into chunks and so I can't find the missing chunks without extensive string matching. 

Nevertheless I'll have a look at the format problem.

**Comment by mauricekraus** [comment]
@Azbagheri Okay played around and now it should work, but I use readarray, which is only supported in plain bash and not in zsh. So in my zsh shell ./gitrise.sh will not work, only bash ./gitrise.sh.

**Comment by Azbagheri** [comment]
The updated script doesn't work on my machine because apparently `readarray` is not supported on macOS. In general it is safer to use the `read` command when possible. Also, just because you mentioned the possibility of using a different shell, I wanted to bring up the fact that we are using shebang in the script to make sure that the script is always run using bash unless the user is overriding it by passing the interpreter at the command line like `zsh ./gitrise.sh`

About the bitrise API that is used, I'm glad you mentioned it because I was going to ask you why you didn't use one of their public APIs. Some of our users are using gitrise for enterprise builds and we are bound to use public APIs. Also, for internal APIs there could be a low limit on the number of calls made externally. We have had that problem even with their public APIs. We're currently using gitrise for builds that are sometime half an hour long and we want to avoid making too many calls to their APIs. That's why we were interested in a streaming method with a variable polling time so that we can control the number of calls and change the polling frequency when we hit the limit of calls.

I do appreciate your effort, but unfortunately we can’t move forward with the PR as is. Please let me know if you are willing to make the changes. Otherwise we leave the issue open and add the feature soon.

**Comment by mauricekraus** [comment]
Okay I get your point, I will try to find another solution and will replace the internal bitrise api with the public one.

**Comment by Azbagheri** [comment]
closing this PR as the feature is now available in [Gitrise v0.8.0](https://github.com/azohra/gitrise.sh/releases/tag/v0.8.0).

**Pull request closed without merging**
